/**
 * Loads the offline demo fixture (public/data/review-center-demo.json —
 * generated by scripts/migration/build-review-fixture.ts from the real
 * Onda 2 dry-run artifacts). Used ONLY as a fallback when the backend is
 * unreachable, so the Review Center's interaction design can still be
 * evaluated. Every screen that ends up using this shows a visible
 * "modo de demonstração" banner — see DemoBanner.tsx.
 */

export interface FixtureOccurrence {
  key: string
  sourceSheet: string
  sourceRow: number
  period: string
  brand: string | null
  model: string | null
  year: number | null
  plate: string | null
  value: number | null
  buyer: string | null
  warnings: string[]
  dataQuality: string
}

export interface FixtureConflict {
  occurrenceA: FixtureOccurrence
  occurrenceBKey: string
  score: number
  reasonsFor: string[]
  reasonsAgainst: string[]
}

export interface FixtureReviewCandidate {
  occurrence: FixtureOccurrence
  score: number
  reasonsFor: string[]
  reasonsAgainst: string[]
}

export interface FixtureInventoryCandidate {
  vehicleCandidateId: string
  brand: string | null
  model: string | null
  version: string | null
  year: number | null
  plate: string | null
  value: number | null
  sourceSheet: string
  sourceRow: number
  confidence: 'high' | 'medium' | 'low'
  warnings: string[]
  priorMonthsSeen: string[]
}

export interface ReviewFixture {
  generatedAt: string
  summary: {
    reviewQueueTotal: number
    conflicts: number
    ambiguousSalesTotal: number
    otherReviewTotal: number
  }
  sales: {
    periodFrom: string | null
    periodTo: string | null
    validDate: number
    invalidDate: number
    ambiguous: number
  }
  currentInventory: FixtureInventoryCandidate[]
  conflicts: FixtureConflict[]
  ambiguousSales: FixtureOccurrence[]
  otherReview: FixtureReviewCandidate[]
}

let cached: Promise<ReviewFixture> | null = null

export function loadReviewFixture(): Promise<ReviewFixture> {
  cached ??= fetch('/data/review-center-demo.json').then((res) => {
    if (!res.ok) throw new Error(`Failed to load review fixture: ${res.status}`)
    return res.json() as Promise<ReviewFixture>
  })
  return cached
}
